language: php

php:
  - 7.0
  - 7.1

before_script:
  - travis_retry composer update

script:
  # check coding standard for our code
  #- vendor/bin/phpcs -p --standard=psr2 src tests
  - vendor/bin/php-cs-fixer fix --config=.php_cs.dist -v --dry-run
  - vendor/bin/phpunit --coverage-clover=coverage.clover
  - phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  # get scrutinizer for coverage upload
  - |
    if [[ $TRAVIS_PHP_VERSION != '7.0' ]]; then
      php vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover
    fi
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
  - travis_retry composer create-project nette/code-checker temp/code-checker ~2.5 --no-interaction

cache:
    directories:
        - $HOME/.composer/cache
